spring:
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
      default_batch_fetch_size: 20
      jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:file:./hack
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  data.rest:
    basePath: /api
    returnBodyOnCreate: true
  logging:
    level:
      root: DEBUG
      lb.ferzshow.bootjava: DEBUG
app:
  jwtSecret: nftFourTask
  jwtExpiration: 86400
server:
  port: 8081
ml:
  address: http://127.0.0.1:5000/json
